# Service Description
info:
  component: greeting-config demo

# End points configuration
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
     
# HTTP server port
#server:
#  port: 1111

# Alter security default behavior
security:
  basic:
    enabled: false # turn off application security

management:
  security:
    enabled: false # turn off actuator endpoints security  

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote